tami5/lspsaga.nvim

- lua/lspsaga/codeaction.lua
Change the texthl argument for the lightbulb sign from
"LspSagaLightBulbSign" to "LspSagaLightBub" so that it match the default
highlight group definition in `plugin/lspsaga.vim`.
https://github.com/glepnir/lspsaga.nvim/pull/235
> Fix a mismatch of lightbulb highlight group name

- README.md
Since it's unknown when Glepnir will return, the README may as well instruct to install from this repo rather than glepnir's.
Thank you for updating the plugin. Your fixes have solved both of the problems I'm having with lspsaga.
> Change repository name in README

- lua/lspsaga/diagnostic.lua
This PR replace the removed function `lsp.diagnostic._get_floating_severity_highlight_name` with a table of highlight floating values in the `show_diagnostics` function of `lspsaga/diagnostic.lua` file, fixing the issue #11. I've used the `neovim` help page for `:help diagnostic-highlight` as reference for the `diagnostic_highlights` table.
Note: The function `lsp.diagnostic._get_floating_severity_highlight_name` that was removed in neovim 0.6.0 (which I can't find the commit of).
> fix: replace deprecated function _get_floating_severity_highlight_name (#11)

- lua/lspsaga/diagnostic.lua
If `vim.diagnostic` yields nil, set diagnostic_highlights as an empty table and
use `lsp.diagnostic._get_floating_severity_highlight_name` to set
highlight name on nvim 0.5.1.
Refers to issue #14 .
> Fix: Diagnostic module for neovim 0.5.1

- README.md
- lua/lspsaga/diagnostic.lua
- lua/lspsaga/init.lua
Need to suppress a line when there is no header. Also give ability to customise prefix for diagnostic messages.
> Added config option 'diagnostic_prefix_format' and fix show_header=false scenario

- lua/lspsaga/provider.lua
I'm using a colorscheme that does not have cursor line bg. I will get error:
```
Vim(highlight):E417: missing argument: guibg=
```
when I close the finder window
> fix empty cursor_line_bg

- lua/lspsaga/init.lua
- lua/lspsaga/rename.lua
Added config option `rename_prompt_populate` to have the rename prompt
begin with the current cursor word.
Set the config option default to true
- This is a common default for similar plugins and functionality
- It is easier to delete a word than it is to type it out
> Rename Prompt Populate Value

- README.md
- lua/lspsaga/diagnostic.lua
The corrected name was not being used. Meaning you have to use the deprecated name, which prints an annoying deprecation warning every time :p.
> Use diagnostic_header_icon instead of dianostic_header_icon.

- lua/lspsaga/diagnostic.lua
- lua/lspsaga/hover.lua
- lua/lspsaga/implement.lua
- lua/lspsaga/libs.lua
- lua/lspsaga/provider.lua
- lua/lspsaga/signaturehelp.lua
removed in neovim master
~PS: i would've made an util function but there seem to be no util(s) module so i did not add one. I can refactor this out somewhere else if you can point it out to me :)~
> fix: remove calls to lsp.util.close_preview_autocmd

- lua/lspsaga/diagnostic.lua
when the buffer is null, the diagnostics returns all errors in the project, which caused the strange behavior of issue #55
> fix: #55 diagnostic shows errors incorrectly

- lua/lspsaga/codeaction.lua
Fixes #44
The code in `lua/lspsaga/codeaction/window.lua` uses the word (number) under the cursor to lookup which action to execute (_the actions are in a 1-based lua array, so that index can be used directly_):
https://github.com/tami5/lspsaga.nvim/blob/main/lua/lspsaga/codeaction/window.lua#L51-L58
This change ensures the words (numbers) that can be under the cursor are correctly incremented for each new action that is inserted into the `window.actions` table.
**Before**
**After**
> Code actions for multiple lsps are correctly numbered.

- lua/lspsaga/codeaction/indicator.lua
When rendering the code action indicator it early returns when the `code_action` capability is not supported by the current LSP. However, it incorrectly tries to detect it as `code_actions` (plural) instead of `code_action`:
After fix:
> fix(code_action.indicator): detection of code_action capability

- lua/lspsaga/rename.lua
I want to add a filetype to rename because I want to add a keymap in the buffer of rename.
```vim
function! s:lspsaga_rename() abort
nnoremap <buffer> <Esc> q
inoremap <buffer> <C-o> <C-r>+
inoremap <buffer> <C-w> <C-S-W>
endfunction
augroup my-lspsaga
autocmd!
autocmd FileType LspSagaRename call s:lspsaga_rename()
augroup END
```
There are several possible names for the filetype, which one do you prefer?
* `lspsagarename`
* `LspSagaRename`
* `LspsagaRename`
> feat(rename): add filetype

- lua/lspsaga/hover.lua
- lua/lspsaga/libs.lua
- lua/lspsaga/signaturehelp.lua
#72
Reuse `focusable_float()` from `signaturehelp.lua` and remove the `BufLeave` event in `close_preview_autocmd`, since this will prevent the jumping into the preview window.
> feat(hover): focus hover window when calling twice

- README.md
- lua/lspsaga/init.lua
- lua/lspsaga/rename.lua
Since [renamer.nvim](https://github.com/filipdutescu/renamer.nvim) used to output to quickfix list, I added a similar feature.
I added an `rename_output_qflist`option, but it defaults to `false`, so you need to set it to true to enable it.
I will describe the options in the wiki, is that OK?
> feat(rename): optional integration of quickfix

- lua/lspsaga/libs.lua
closes #81.
I also remove the mappings `<Esc>` and `<C-c>` from the hover window.
Since we have previously discussed using filetype autocmd for that.
> fix(signaturehelp): avoid jumping to floating window

- lua/lspsaga/codeaction/indicator.lua
Fix #67 
When I open some python file and then open some another python file I have the error 
```
Error detected while processing CursorHold Autocommands for "*":
method textDocument/codeAction is not supported by any of the servers registered for the current buffer
```
This is because nvim runs a new copy of lsp for each opened python file. So it seems wrong copy of pylsp gave `M.servers[current_file] = true`.
I think the code is definitely better now. But the thing I have doubts about is that after some time the condition 
```lua
if
is_file
and client
and client.config.filetypes
and vim.tbl_contains(client.config.filetypes, fb)
and client.resolved_capabilities.code_action
and client.supports_method "code_action"
then
```
becomes `true`. So lspsaga should retry to attach after some …
> enh(actions.indicator): rework

- lua/lspsaga/command.lua
- lua/lspsaga/diagnostic.lua
Close #50.
Usage:
`:Lspsaga diagnostic_yank_messages` yanks the last messages to vim default registry (the same used by the `y` key).
`:Lspsaga diagnostic_yank_messages +` yanks the last messages to system's clipboard (any other registry can be used).
It's my first time playing with Neovim plugins and Lua, so feel free to correct me if i messed up.
> feat(diagnostic): yank diagnostics messages

- lua/lspsaga/codeaction.lua
sumneko_lua sometimes responds with absurdly long multiline code actions, which makes `nvim_buf_set_lines` fail (throws "String cannot contain newlines")
It can be reproduced with the following code, hovering over `ev` and opening the codeactions buffer
```lua
local t = {
on_reload = function (ev, bufnr)
--
end
}
```
Fixed it by limiting actions to a single line, I don't think it makes sense to attempt to show all of the response
> Fixed error with multiline code actions 

- lua/lspsaga/codeaction/window.lua
Pull ctx to local scope because the close function gets called from the
execute callback and sets the module ctx variable to nil.
Fixes #59
> fix(codeaction/window) ctx cleared before use
